# Generated by Django 5.1.4 on 2024-12-29 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Drink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("flavor_tags", models.TextField(blank=True, null=True)),
                ("customizable_sweetness", models.BooleanField(default=False)),
                ("contains_caffeine", models.BooleanField(default=False)),
                ("contains_gluten", models.BooleanField(default=False)),
                ("oat_milk_substitution", models.BooleanField(default=False)),
                ("vegan_friendly", models.BooleanField(default=False)),
                ("contains_dairy", models.BooleanField(default=False)),
            ],
        ),
    ]
