# Generated by Django 5.1.4 on 2024-12-30 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=100, unique=True)),
                ("ip_address", models.GenericIPAddressField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="drink",
            name="contains_caffeine",
        ),
        migrations.RemoveField(
            model_name="drink",
            name="contains_dairy",
        ),
        migrations.RemoveField(
            model_name="drink",
            name="contains_gluten",
        ),
        migrations.RemoveField(
            model_name="drink",
            name="oat_milk_substitution",
        ),
        migrations.RemoveField(
            model_name="drink",
            name="vegan_friendly",
        ),
        migrations.AlterField(
            model_name="drink",
            name="flavor_tags",
            field=models.TextField(default="Default Flavor Tag"),
        ),
        migrations.AlterField(
            model_name="drink",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item", models.CharField(max_length=100)),
                ("rating", models.IntegerField()),
                ("purchased", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.user"
                    ),
                ),
            ],
        ),
    ]
