# Generated by Django 5.1.4 on 2024-12-30 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_user_remove_drink_contains_caffeine_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="ip_address",
        ),
    ]
