# Generated by Django 5.1.4 on 2024-12-30 21:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_remove_user_ip_address"),
    ]

    operations = [
        migrations.RenameField(
            model_name="feedback",
            old_name="item",
            new_name="base_type",
        ),
        migrations.RemoveField(
            model_name="feedback",
            name="purchased",
        ),
        migrations.AddField(
            model_name="feedback",
            name="category",
            field=models.CharField(default="DefaultCategory", max_length=100),
        ),
        migrations.AddField(
            model_name="feedback",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="feedback",
            name="recommendation",
            field=models.CharField(default="Default Recommendation", max_length=255),
        ),
        migrations.AddField(
            model_name="feedback",
            name="selected_tags",
            field=models.TextField(default="Default Tag"),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="rating",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
